In [1]:
import json
import os
import matplotlib.pyplot as plt
import numpy as np
from qiskit_experiments.framework import (
    ExperimentData,
    ExperimentDecoder,
    ExperimentEncoder,
)
from qiskit_research.mzm_generation import KitaevHamiltonianAnalysis

In [2]:
data_raw = []
data_list = []

In [3]:
filename = "2022-07-06T15:23:06.662625_ibmq_guadalupe_n6"

basedir = "/Users/georgezhou/Documents/GitHub/qiskit-research/docs/mzm_generation"

with open(os.path.join(basedir, "data/ibmq_guadalupe", f"{filename}.json")) as f:
    # this may raise an error from Qiskit Experiments but it should be safe to ignore
    data_raw.append(json.load(f, cls=ExperimentDecoder))

/Users/georgezhou/miniforge3/envs/DDResearch/lib/python3.9/site-packages/qiskit_experiments/framework/json.py:584: UserWarning: Could not deserialize instance of class <class 'qiskit.providers.ibmq.accountprovider.AccountProvider'> from settings {}. 
The following exception was raised:
Traceback (most recent call last):
  File "/Users/georgezhou/miniforge3/envs/DDResearch/lib/python3.9/site-packages/qiskit_experiments/framework/json.py", line 338, in _deserialize_object
    return cls(**settings)
TypeError: __init__() missing 2 required positional arguments: 'credentials' and 'factory'

  return _deserialize_object(obj_val)
/Users/georgezhou/miniforge3/envs/DDResearch/lib/python3.9/site-packages/qiskit_experiments/framework/json.py:584: UserWarning: Could not deserialize instance of class <class 'qiskit_research.mzm_generation.experiment.KitaevHamiltonianExperiment'> from value ExperimentConfig(cls=<class 'qiskit_research.mzm_generation.experiment.KitaevHamiltonianExperiment'>, args=[{

In [4]:
analysis = KitaevHamiltonianAnalysis()
data = analysis.run(data_raw[-1], replace_results=True)
data.block_for_results()
data_list.append(data)

/Users/georgezhou/miniforge3/envs/DDResearch/lib/python3.9/site-packages/numpy/linalg/linalg.py:2146: RuntimeWarning: divide by zero encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/georgezhou/miniforge3/envs/DDResearch/lib/python3.9/site-packages/numpy/linalg/linalg.py:2146: RuntimeWarning: invalid value encountered in det
  r = _umath_linalg.det(a, signature=signature)
/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:697: RuntimeWarning: overflow encountered in matmul
  error = cast(float, np.linalg.norm(mat @ mat - mat))
/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:697: RuntimeWarning: invalid value encountered in matmul
  error = cast(float, np.linalg.norm(mat @ mat - mat))


{'010000': 2, '010010': 85, '010011': 55, '010110': 92, '010111': 60, '011000': 1, '011001': 1, '011010': 354, '011011': 199, '011100': 4, '011110': 401, '011111': 230, '110000': 9, '110001': 5, '110010': 531, '110011': 315, '110100': 8, '110101': 3, '110110': 567, '110111': 348, '111000': 21, '111001': 19, '111010': 1981, '111011': 1212, '111100': 18, '111101': 10, '111110': 2166, '111111': 1303}
{'010000': 1, '010001': 3, '010010': 126, '010011': 104, '010101': 2, '010110': 179, '010111': 192, '011000': 6, '011001': 6, '011010': 237, '011011': 240, '011100': 2, '011101': 5, '011110': 532, '011111': 595, '110000': 12, '110001': 4, '110010': 410, '110011': 350, '110100': 1, '110101': 7, '110110': 723, '110111': 642, '111000': 14, '111001': 11, '111010': 797, '111011': 853, '111100': 13, '111101': 13, '111110': 1900, '111111': 2020}
{'010010': 81, '010011': 45, '010101': 1, '010110': 61, '010111': 38, '011000': 1, '011001': 2, '011010': 468, '011011': 307, '011100': 4, '011101': 4, '011

/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:696: RuntimeWarning: overflow encountered in matmul
  mat = mat @ mat @ (three - 2 * mat)
/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:696: RuntimeWarning: invalid value encountered in matmul
  mat = mat @ mat @ (three - 2 * mat)


{'010000': 4, '010010': 309, '010011': 74, '010110': 84, '010111': 25, '011000': 6, '011001': 4, '011010': 808, '011011': 202, '011100': 1, '011110': 270, '011111': 66, '110000': 12, '110001': 4, '110010': 1259, '110011': 244, '110100': 11, '110101': 1, '110110': 483, '110111': 134, '111000': 48, '111001': 9, '111010': 3545, '111011': 762, '111100': 28, '111101': 8, '111110': 1209, '111111': 390}
{'010000': 4, '010010': 227, '010011': 107, '010100': 3, '010101': 1, '010110': 292, '010111': 89, '011000': 8, '011001': 3, '011010': 496, '011011': 176, '011100': 10, '011101': 4, '011110': 527, '011111': 179, '101110': 1, '110000': 16, '110001': 7, '110010': 928, '110011': 382, '110100': 11, '110101': 6, '110110': 1058, '110111': 380, '111000': 26, '111001': 14, '111010': 1726, '111011': 699, '111100': 37, '111101': 12, '111110': 1943, '111111': 628}
{'010000': 2, '010010': 73, '010011': 35, '010110': 73, '010111': 54, '011000': 2, '011001': 1, '011010': 194, '011011': 102, '011100': 5, '01

/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:331: RuntimeWarning: invalid value encountered in multiply
  operator.hermitian_part * corr[:n, :n]
/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:332: RuntimeWarning: invalid value encountered in multiply
  + np.real(operator.antisymmetric_part * corr[:n, n:])
/Users/georgezhou/Documents/GitHub/qiskit-research/qiskit_research/mzm_generation/utils.py:383: RuntimeWarning: invalid value encountered in cdouble_scalars
  coeff * corr[i + n * (action_i == "-"), j + n * (action_j == "+")]


In [6]:
params = []
fidelity_witness_avg = []
energy_exact = []
energy = []
energy_error = []
bdg_energy_exact = []
bdg_energy = []
edge_correlation_exact = []
edge_correlation = []
number_exact = []
number = []
parity_exact = []
parity = []
site_correlation_exact = []
site_correlation = []
for data in data_list:
    params.append(data.metadata["params"])

# load results
    fidelity_witness_avg.append(data.analysis_results("fidelity_witness_avg").value)
    energy_exact.append(data.analysis_results("energy_exact").value)
    energy.append(data.analysis_results("energy").value)
    energy_error.append(data.analysis_results("energy_error").value)
    bdg_energy_exact.append(data.analysis_results("bdg_energy_exact").value)
    bdg_energy.append(data.analysis_results("bdg_energy").value)
    edge_correlation_exact.append(data.analysis_results("edge_correlation_exact").value)
    edge_correlation.append(data.analysis_results("edge_correlation").value)
    number_exact.append(data.analysis_results("number_exact").value)
    number.append(data.analysis_results("number").value)
    parity_exact.append(data.analysis_results("parity_exact").value)
    parity.append(data.analysis_results("parity").value)
    site_correlation_exact.append(data.analysis_results("site_correlation_exact").value)
    site_correlation.append(data.analysis_results("site_correlation").value)

# create plot directory
PLOT_DIR = f"plots/Guadalupe_n_experiment"
os.makedirs(PLOT_DIR, exist_ok=True)

# set plot options
dpi = 150
filetype = "pdf"

# print(params)

In [10]:
print(data_list)

---------------------------------------------------
Experiment: KitaevHamiltonianExperiment
Experiment ID: 072880cd-6016-475b-a5bf-934a6322aae6
Status: ExperimentStatus.DONE
Data: 1560
Analysis Results: 16
Figures: 0


In [8]:
energy_error[-1]

{None: {'raw': (array([ 5.33211667,  5.82932103,  7.00916805,  8.65535896, 10.48076521]),
   array([0.00628454, 0.0068711 , 0.00833537, 0.01021974, 0.01246542]),
   array([1.77737222, 1.5106651 , 1.3972416 , 1.3685087 , 1.3599727 ])),
  'mem': (array([ 5.38595232,  5.88457777,  7.07556529,  8.7254967 , 10.57318475]),
   array([0.00831963, 0.00915618, 0.01110006, 0.01349275, 0.01650517]),
   array([1.79531744, 1.52498486, 1.41047755, 1.37959826, 1.37196496])),
  'ps': (array([ 5.43518619,  5.79507626,  6.98618005,  8.65170686, 10.47701348]),
   array([0.01204374, 0.01276992, 0.01554071, 0.01875597, 0.02264974]),
   array([1.81172873, 1.5017906 , 1.39265906, 1.36793127, 1.35948588])),
  'pur': (array([5.19286975e+248, 1.09665679e+264, 1.83510543e+262,             nan,
                      nan]),
   array([0.01204374, 0.01276992, 0.01554071, 0.01875597, 0.02264974]),
   array([1.73095658e+248, 2.84197959e+263, 3.65818828e+261,             nan,
                      nan]))},
 'X2pm': {'ra